import './_tabs';
import './_modal';
// import './_initRellax';
import './_resizeTextarea';
import './_scrollTrigger';
import './_validation';
import './_heroAnim';
import './_headerToggler';
import './_cookies';
import './_scrollTo';
